alleyinteractive/wp-alleyvate

.gitignore
src/alley/wp/alleyvate/load.php
wp-alleyvate.php

Ensure that the plugin does not fatal if Composer is not installed.

Bail if the Composer dependencies are not loaded to prevent a fatal

---

CHANGELOG.md
README.md
composer.json
src/alley/wp/alleyvate/features/class-disable-sticky-posts.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-disable-comments.php
tests/alley/wp/alleyvate/features/test-disable-sticky-posts.php

Disable sticky posts in the admin for both the classic editor and Gutenberg.
Added `Refresh_Database` trait to Disable Comments test because of an error in Mantle that will need fixing:
```
Alley\WP\Alleyvate\Features\Test_Disable_Sticky_Posts::test_disable_action_sticky_rest_api_edit
Mantle\Database\Model\Model_Exception: Error saving model: Sorry, that username already exists!
```
Resolves #41.
The tests for this had to be written to inspect the homepage query versus making a raw `WP_Query` because sticky posts are only applied on the homepage.
* Added feature to disable sticky posts in WordPress.

Disable Sticky Posts

---

composer.json
src/alley/wp/alleyvate/features/class-disable-dashboard-widgets.php
tests/alley/wp/alleyvate/features/test-clean-admin-bar.php
tests/alley/wp/alleyvate/features/test-disable-comments.php
tests/alley/wp/alleyvate/features/test-disable-dashboard-widgets.php
tests/alley/wp/alleyvate/features/test-disable-sticky-posts.php

- Upgrading Mantle TestKit to 0.12 and Alley Coding Standards (WPCS) to 2.0.
- Fixing coding standards to match Alley Coding Standards 2.0.
- Preventing an external HTTP request during testing.

Chore: Upgrading dependencies

---

CHANGELOG.md
src/alley/wp/alleyvate/features/class-disable-comments.php
wp-alleyvate.php

- As titled;
- `action__init` method phpDoc description updated to be more general;
- fixes #60 
- CHANGELOG updated with latest changes;
- Plugin version updated since it is outdated as per the [recent releases](https://github.com/alleyinteractive/wp-alleyvate/releases/tag/v2.2.0).
None.

Akismet: Removes the comment spam queue section from the WP dashboard

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-disable-comments.php
src/alley/wp/alleyvate/features/class-disable-custom-fields-meta-box.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/concerns/trait-remove-meta-box.php
tests/alley/wp/alleyvate/features/test-disable-comments.php
tests/alley/wp/alleyvate/features/test-disable-custom-fields-meta-box.php

- Removes the 'Custom Fields' meta box. 
- Removes the `commentstatusdiv` meta box when comments are disabled.
Resolves #23.

Disable custom fields meta box

---

CHANGELOG.md
src/alley/wp/alleyvate/features/class-login-nonce.php
tests/alley/wp/alleyvate/features/test-login-nonce.php
wp-alleyvate.php

Make sure the nonce lifetime is run only for the login action as to not affect the other `wp-login.php` actions, e.g: logout.
Currently, when trying to log out, the `log-out` nonce mismatch (since it is changed) and a user sees the following screen:
None.

Login Nonce: nonce lifetime is changed only for the login action

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-prevent-framing.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-prevent-framing.php

Adding X-Frame-Options/Content-Security-Policy headers

---

CHANGELOG.md
phpunit.xml
src/alley/wp/alleyvate/features/class-disable-attachment-routing.php
tests/alley/wp/alleyvate/features/concerns/trait-remove-meta-box.php
tests/alley/wp/alleyvate/features/test-clean-admin-bar.php
tests/alley/wp/alleyvate/features/test-disable-attachment-routing.php
tests/alley/wp/alleyvate/features/test-disable-comments.php
tests/alley/wp/alleyvate/features/test-disable-custom-fields-meta-box.php
tests/alley/wp/alleyvate/features/test-disable-dashboard-widgets.php
tests/alley/wp/alleyvate/features/test-disable-password-change-notification.php
tests/alley/wp/alleyvate/features/test-disable-sticky-posts.php
tests/alley/wp/alleyvate/features/test-disable-trackbacks.php
tests/alley/wp/alleyvate/features/test-disallow-file-edit.php
tests/alley/wp/alleyvate/features/test-login-nonce.php
tests/alley/wp/alleyvate/features/test-prevent-framing.php
tests/alley/wp/alleyvate/features/test-redirect-guess-shortcircuit.php
tests/alley/wp/alleyvate/features/test-site-health.php
tests/alley/wp/alleyvate/features/test-user-enumeration-restrictions.php

Misc changes to the unit tests

---

.github/workflows/tests.yml
.php-cs-fixer.dist.php
composer.json
src/alley/wp/alleyvate/features/class-full-page-cache-404.php
tests/alley/wp/alleyvate/features/test-full-page-cache-404.php
tests/bootstrap.php

As titled.
See https://github.com/alleyinteractive/wp-alleyvate/pull/46

[Feature] Unit tests for the Full-Page Caching for 404s feature

---

src/alley/wp/alleyvate/features/class-full-page-cache-404.php
tests/alley/wp/alleyvate/features/test-full-page-cache-404.php

The "Full-Page Caching for 404s" feature requires ssl

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-remove-shortlink.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-remove-shortlink.php

Adds a new feature to remove the shortlink tag from the head of the page.
Resolves #38

Remove shortlink from the head of the page

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-cache-slow-queries.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-cache-slow-queries.php
tests/alley/wp/alleyvate/features/test-disable-comments.php

Add a feature to cache the slow months query dropdown in the admin.

Cache Months Dropdown in Admin

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-disable-pantheon-constant-overrides.php
src/alley/wp/alleyvate/load.php

Pantheon site protocol scheme should match the db value regardless of request type.
None.
- Feature to disable WP_SITEURL and WP_HOME for Pantheon environments. This ensures the Pantheon site's protocol scheme matches the database values for `siteurl` and `home`, enhancing consistency across different request types. 
- Manipulates protocol scheme for HTTP requests in Pantheon-maintains a `wp-config-pantheon.php` file to ensure site's domain protocol matches the protocol in the database options for `siteurl` and `home` for non-http requests as well. [#85](https://github.com/alleyinteractive/wp-alleyvate/issues/85)

Issue-85: Pantheon site protocol scheme should match the db value regardless of request type

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-disable-deep-pagination.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-disable-deep-pagination.php

Closes #42 
As titled. This update disables deep pagination beyond page 100 for both frontend and unauthenticated REST requests, with added flexibility to customize this limit.
Please review the implementation of the deep pagination disable feature and note the adjustments for coding standards compliance.
- Disable pagination past page 100 for frontend and unauthenticated REST requests. Allow customization of the limit. [#42](https://github.com/alleyinteractive/wp-alleyvate/issues/42)
- Addressed PHPCS issues related to the deep pagination feature.

Issue-42: [FEATURE] Disable deep pagination

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-force-two-factor-authentication.php
src/alley/wp/alleyvate/load.php

As titled.
None.
- Force 2FA for all users who can edit content on WordPress VIP sites, sites that use Jetpack, and sites that use the Two Factor plugin. [#55](https://github.com/alleyinteractive/wp-alleyvate/issues/55)
- Implemented a security measure requiring users to set up Two-Factor Authentication (2FA) before being able to edit anything other than their profile. This measure is aimed at enhancing the security of WordPress VIP sites, Jetpack-enabled sites, and sites using the Two Factor plugin. References to Jetpack and VIP's 2FA implementation were considered during the discussion. [#55](https://github.com/alleyinteractive/wp-alleyvate/issues/55)

Issue-55: [FEATURE] Force 2FA for All Users Who Can Edit Content

---

.php-cs-fixer.dist.php
CHANGELOG.md
README.md
composer.json
src/alley/wp/alleyvate/features/class-disable-block-editor-rest-api-preload-paths.php
src/alley/wp/alleyvate/load.php
tests/alley/wp/alleyvate/features/test-disable-block-editor-rest-api-preload-paths.php

WordPress pre-loads all Reusable Blocks (Synced Patterns) on the edit post screen, site editor, and widget screen. For sites with hundreds of blocks, this is a lot of processing overhead, as the_content and all other filters run on these blocks. Disabling this behavior make the editing experience faster and less fragile for sites with a large number of blocks.
None.

Issue-91 [FEATURE] Removes preloading of blocks on edit post screen

---

src/alley/wp/alleyvate/features/class-force-two-factor-authentication.php

As titled. Fixes #95
None.
- Fixed an issue where creating a new user without enabling two-factor authentication (2FA) led to a 502 nginx error on login. This was caused by an infinite loop in the Alleyvate plugin on WordPress VIP environments. The solution involves modifying the plugin's logic to prevent this loop.

Issue-95: force_two_factor_authentication feature causing 502 errors on VIP

---

CHANGELOG.md
src/alley/wp/alleyvate/features/class-disable-attachment-routing.php

The previous implementation, on `pre_get_posts`, ran too early to prevent this redirect. It was still possible for a query to be set to `is_attachment` after `pre_get_posts` ([example](https://github.com/WordPress/wordpress-develop/blob/1e21ecedf19f1b97360949a9e509a3c04ac1f34e/src/wp-includes/class-wp-query.php#L2175-L2179)), and that was enough to trigger the redirect to the attachment URL in `redirect_canonical()` ([source](https://github.com/WordPress/wordpress-develop/blob/1e21ecedf19f1b97360949a9e509a3c04ac1f34e/src/wp-includes/canonical.php#L552-L571)). 
In the approach taken here, the query is allowed to complete normally, determining conditionals like `is_attachment`, before being inspected and overridden later if necessary.
None.
* The `disable_attachment_routing` feature now …

Disable attachment redirects to files

---

.github/workflows/all-pr-tests.yml
CHANGELOG.md
src/alley/wp/alleyvate/features/class-login-nonce.php

As titled. Fixes #70
None.
- Refresh mechanism for persisted pages to ensure nonce validation.
- Unnecessary nonce validation check that failed for empty values.

Issue-70: Bug: Login Nonce fails for pages \"cached\" by bfcache

---

.github/workflows/all-pr-tests.yml
CHANGELOG.md
composer.json
package.json
tests/Alley/WP/Alleyvate/Features/DisableAppleNewsNonProdPushTest.php
wp-alleyvate.php

- Adds support for v2-3 of `alleyinteractive/wp-type-extensions`.

Add support for alleyinteractive/wp-type-extensions 3.0

---

CHANGELOG.md
README.md
src/alley/wp/alleyvate/features/class-twitter-embeds.php
tests/Alley/WP/Alleyvate/Features/TwitterEmbedsTest.php

As titled.
None.
* Removed fsockopen backstop option for Twitter/X oEmbeds.

Remove fsockopen Twitter oEmbed backstop

---

src/alley/wp/alleyvate/features/class-disable-deep-pagination.php
tests/Alley/WP/Alleyvate/Features/DisableDeepPaginationTest.php

Ensure that the pagination system never provides links to pages beyond page 100. The number should max out at 100, and if you are on page 100, an “older” link should not display.
If a user attempts to access a page beyond 100, return an HTTP 410 response.
None.

Pagination max should be 100 and error 410
